### ISSUE TITLE
Images too big in PDF?

### ISSUE THREAD

**Issue by jkfindeisen** [AbberiorInstruments/ImspectorDocs#2]
The images in the html output look rather largish but still okay. In the PDF output however (which goes through Latex internally) they are definitely too big.

Is this a feature or a bug?

Is there a way to have the images/figures scaled down in PDF output as compared to html output using Sphinx?

**Comment by mpibpc-mroose** [comment]
From the troubleshooting I assume PIL missing in the requirements file.

**Comment by mpibpc-mroose** [comment]
fixed in 56c69ee

**Comment by mpibpc-mroose** [comment]
maybe one has to play with http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

**Comment by jkfindeisen** [comment]
I reopen the issue because images in the PDF still do not look good. They are too big. Question is how to make them a bit smaller without changing output size in HTML output much. I will look at the link of Marco and play around with it when there is time.
